Use "clang -w -target bpf -nostdlibinc ..." instead of "clang -w -target bpf", to fix build error:
clang bpf /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
(/usr/include got used instead of the clang includes)